server:
    port: 8080
    #servlet:
    #  context-path: /v1
spring:
  application:
    name: ms-user
  docker:
    compose:
      enabled: true
      file: ./../docker-compose.yml
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    virtual-host: /

  datasource:
    url: jdbc:mysql://localhost:3307/db_users?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
security:
  jwt:
    secret-key: 4662a111eccdc722582a89543a294e898e9888a9d2f96f6baa1a326f99e4908c  #HMAC-256
    expiration-time: 3600000