server:
    port: 8080
    servlet:
      context-path: /v1
spring:
  application:
    name: ms-user
  rabbitmq:
    host: localhost
    port: 5672
  datasource:
    url: jdbc:mysql://localhost:3306/db_users?createDatabaseIfNotExist=true
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
