server:
    port: 8080
    servlet:
      context-path: /v1

spring:
  application:
    name: ms-user
  datasource:
    url: jdbc:mysql://localhost:3307/db_users?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true #desativar em prod
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

